# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 02:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='How one would call this donation category', max_length=256, verbose_name='Category name')),
                ('description', models.CharField(default='', help_text='A small description of the category and its contents', max_length=256, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', help_text='a small description of the donation', max_length=1024)),
                ('date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(help_text='How one would classify the donation: money, food, etc.', on_delete=django.db.models.deletion.CASCADE, related_name='donations', related_query_name='donation', to='donations.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'donation',
                'verbose_name_plural': 'donations',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, help_text="Donor's name", max_length=512, verbose_name='Donor Name')),
                ('integration_date', models.DateField(default=datetime.date.today, help_text='Date when the donor is integrated into Vifac', verbose_name='Integration Date')),
                ('state', models.PositiveIntegerField(choices=[(0, 'Ninguno'), (1, 'Aguascalientes'), (2, 'Baja California'), (3, 'Baja California Sur'), (4, 'Campeche'), (5, 'Chiapas'), (6, 'Chihuahua'), (7, 'Ciudad de México'), (8, 'Coahuila de Zaragoza'), (9, 'Colima'), (10, 'Durango'), (11, 'Guanajuato'), (12, 'Guerrero'), (13, 'Hidalgo'), (14, 'Jalisco'), (15, 'Estado de México'), (16, 'Michoacán de Ocampo'), (17, 'Morelos'), (18, 'Nayarit'), (19, 'Nuevo León'), (20, 'Oaxaca'), (21, 'Puebla'), (22, 'Querétaro de Arteaga'), (23, 'Quintana Roo'), (24, 'San Luis Potosí'), (25, 'Sinaloa'), (26, 'Sonora'), (27, 'Tabasco'), (28, 'Tamaulipas'), (29, 'Tlaxcala'), (30, 'Veracruz'), (31, 'Yucatán'), (32, 'Zacatecas')], default=0, verbose_name='State')),
                ('city', models.CharField(default='', max_length=256, verbose_name='City')),
                ('street', models.CharField(default='', max_length=256, verbose_name='Street')),
                ('number', models.CharField(default='', max_length=8, verbose_name='Number')),
                ('reference', models.CharField(default='', help_text='Whoever introduced the donor to Vifac', max_length=256, verbose_name='Reference')),
                ('contact_name', models.CharField(default='', help_text="Contact's name", max_length=512, verbose_name='Contact Name')),
                ('contact_email', models.EmailField(blank=True, help_text="Contact's Email", max_length=256)),
                ('contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('contact_birthday', models.DateField(blank=True)),
                ('contact_anniversary', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'donor',
                'verbose_name_plural': 'donations',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', related_query_name='donation', to='donations.Donor'),
        ),
    ]
