# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.ForeignKey(help_text='How one would classify the donation: money, food, etc.', on_delete=django.db.models.deletion.PROTECT, related_name='donations', related_query_name='donation', to='donations.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', related_query_name='donation', to='donations.Donor'),
        ),
    ]
