# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20170322_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'verbose_name': 'donor', 'verbose_name_plural': 'donors'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.ForeignKey(help_text='How one would classify the donation: money, food, etc.', on_delete=django.db.models.deletion.CASCADE, related_name='donations', related_query_name='donation', to='donations.Category', verbose_name='Category'),
        ),
    ]
