# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 05:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panfleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=15)),
                ('devuelta', models.BooleanField(default=False)),
                ('monto_entregado', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1250)])),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Participante's name", max_length=512, verbose_name='Participante Name')),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='panfleta',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffles.Participante'),
        ),
    ]
