# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fRegistro', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=256)),
                ('aPaterno', models.CharField(default='', max_length=256)),
                ('aMaterno', models.CharField(default='', max_length=256)),
                ('FNacimiento', models.DateField()),
                ('Estado', models.PositiveIntegerField(choices=[(0, 'Ninguno'), (1, 'Aguascalientes'), (2, 'Baja California'), (3, 'Baja California Sur'), (4, 'Campeche'), (5, 'Chiapas'), (6, 'Chihuahua'), (7, 'Ciudad de México'), (8, 'Coahuila de Zaragoza'), (9, 'Colima'), (10, 'Durango'), (11, 'Guanajuato'), (12, 'Guerrero'), (13, 'Hidalgo'), (14, 'Jalisco'), (15, 'Estado de México'), (16, 'Michoacán de Ocampo'), (17, 'Morelos'), (18, 'Nayarit'), (19, 'Nuevo León'), (20, 'Oaxaca'), (21, 'Puebla'), (22, 'Querétaro de Arteaga'), (23, 'Quintana Roo'), (24, 'San Luis Potosí'), (25, 'Sinaloa'), (26, 'Sonora'), (27, 'Tabasco'), (28, 'Tamaulipas'), (29, 'Tlaxcala'), (30, 'Veracruz'), (31, 'Yucatán'), (32, 'Zacatecas')], default=0)),
                ('Telefono', models.CharField(default='', max_length=256)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoptions.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=256)),
                ('aPaterno', models.CharField(default='', max_length=256)),
                ('aMaterno', models.CharField(default='', max_length=256)),
                ('FNacimiento', models.DateField()),
                ('Estado', models.PositiveIntegerField(choices=[(0, 'Ninguno'), (1, 'Aguascalientes'), (2, 'Baja California'), (3, 'Baja California Sur'), (4, 'Campeche'), (5, 'Chiapas'), (6, 'Chihuahua'), (7, 'Ciudad de México'), (8, 'Coahuila de Zaragoza'), (9, 'Colima'), (10, 'Durango'), (11, 'Guanajuato'), (12, 'Guerrero'), (13, 'Hidalgo'), (14, 'Jalisco'), (15, 'Estado de México'), (16, 'Michoacán de Ocampo'), (17, 'Morelos'), (18, 'Nayarit'), (19, 'Nuevo León'), (20, 'Oaxaca'), (21, 'Puebla'), (22, 'Querétaro de Arteaga'), (23, 'Quintana Roo'), (24, 'San Luis Potosí'), (25, 'Sinaloa'), (26, 'Sonora'), (27, 'Tabasco'), (28, 'Tamaulipas'), (29, 'Tlaxcala'), (30, 'Veracruz'), (31, 'Yucatán'), (32, 'Zacatecas')], default=0)),
                ('Telefono', models.CharField(default='', max_length=256)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoptions.Family')),
            ],
        ),
    ]
