# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='cartaDIF',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='family',
            name='comprobanteDom',
            field=models.BooleanField(default=False, help_text='Comprobante de Domicilio'),
        ),
        migrations.AddField(
            model_name='family',
            name='estudioPsi',
            field=models.BooleanField(default=False, help_text='Estudio psicologa'),
        ),
        migrations.AddField(
            model_name='family',
            name='estudioSC',
            field=models.BooleanField(default=False, help_text='Estudio socioeconomico'),
        ),
        migrations.AddField(
            model_name='family',
            name='fBaja',
            field=models.DateField(auto_now=True, help_text='Fecha que paso de Vivos a Muertos'),
        ),
        migrations.AddField(
            model_name='family',
            name='motivoBaja',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='family',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Vivos'), (1, 'Muertos'), (2, 'Stand By')], default=0),
        ),
    ]
