# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_auto_20170327_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='nombreFam',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
