# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=15)),
                ('aPaterno', models.CharField(max_length=140)),
                ('aMaterno', models.CharField(max_length=140)),
                ('fNacimiento', models.DateField(default='')),
                ('calle', models.CharField(default='', max_length=50)),
                ('colonia', models.CharField(default='', max_length=50)),
                ('cP', models.IntegerField()),
            ],
        ),
    ]
