# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='migrante',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('No', 'No'), ('Sí', 'Sí')], help_text='Migrante', max_length=24, verbose_name='Migrante'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='telefono_emergencia',
            field=models.CharField(blank=True, default='', help_text='Teléfono de emergencia', max_length=24, null=True, verbose_name='Teléfono de emergencia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='telefono_medico',
            field=models.CharField(blank=True, default='', help_text='Teléfono de médico', max_length=24, null=True, verbose_name='Teléfono de médico'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='telefono_recomendacion',
            field=models.CharField(blank=True, default='', help_text='Teléfono de recomendacion', max_length=24, null=True, verbose_name='Teléfono  de recomendacion'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='telefono_vives',
            field=models.CharField(blank=True, default='', help_text='Teléfono  de la persona con quien vives', max_length=24, null=True, verbose_name='Teléfono '),
        ),
    ]
