# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20170423_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='document',
            field=models.FileField(upload_to='documents/', verbose_name='Documento'),
        ),
    ]
