# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20170423_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='calle',
            field=models.CharField(blank=True, default='', help_text='Calle', max_length=256, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='calle_vives',
            field=models.CharField(blank=True, default='', help_text='Calle', max_length=256, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='ciudad',
            field=models.CharField(blank=True, default='', help_text='Ciudad', max_length=256, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='ciudad_vives',
            field=models.CharField(blank=True, default='', help_text='Ciudad', max_length=256, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='codigo_postal',
            field=models.CharField(blank=True, default='', help_text='Código  Postal', max_length=128, null=True, verbose_name='Código  Postal'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='codigo_postal_vives',
            field=models.CharField(blank=True, default='', help_text='Código Postal', max_length=128, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='colonia_vives',
            field=models.CharField(blank=True, default='', help_text='Colonia', max_length=256, null=True, verbose_name='Colonia Vives'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo'), ('Unión Libre', 'Unión Libre'), ('Otro', 'Otro')], default='', help_text='Estado Civil', max_length=128, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='lugar_dentro_familia',
            field=models.CharField(blank=True, default='', help_text='Lugar dentro de la familia', max_length=128, null=True, verbose_name='Lugar dentro de la familia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='madre_apellido_materno',
            field=models.CharField(blank=True, default='', help_text='Apellido Materno', max_length=256, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='madre_apellido_paterno',
            field=models.CharField(blank=True, default='', help_text='Apellido Paterno', max_length=256, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='madre_calle',
            field=models.CharField(blank=True, default='', help_text='Calle', max_length=256, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='madre_ciudad',
            field=models.CharField(blank=True, default='', help_text='Ciudad', max_length=256, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='madre_codigo_postal',
            field=models.CharField(blank=True, default='', help_text='Código  Postal', max_length=128, null=True, verbose_name='Código  Postal'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='madre_colonia',
            field=models.CharField(blank=True, default='', help_text='Colonia', max_length=256, null=True, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='madre_estado',
            field=models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('CDMX', 'Ciudad de México'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Estado de México', 'Estado de México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], default='', help_text='Estado', max_length=256, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='madre_estado_civil',
            field=models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo'), ('Unión Libre', 'Unión Libre'), ('Otro', 'Otro')], default='', help_text='Estado Civil', max_length=128, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='madre_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre', max_length=256, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='madre_ocupacion',
            field=models.CharField(blank=True, default='', help_text='Ocupación', max_length=128, null=True, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='madre_telefono_casa',
            field=models.CharField(blank=True, default='', help_text='Teléfono  de casa', max_length=24, null=True, verbose_name='Teléfono  de casa'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='madre_telefono_particular',
            field=models.CharField(blank=True, default='', help_text='Teléfono  de particular', max_length=24, null=True, verbose_name='Teléfono  particular'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='migrante',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('No', 'No'), ('Sí', 'Sí')], help_text='Migrante', max_length=24, null=True, verbose_name='Migrante'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='padre_apellido_materno',
            field=models.CharField(blank=True, default='', help_text='Apellido Materno', max_length=256, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='padre_apellido_paterno',
            field=models.CharField(blank=True, default='', help_text='Apellido Paterno', max_length=256, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='padre_calle',
            field=models.CharField(blank=True, default='', help_text='Calle', max_length=256, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='padre_ciudad',
            field=models.CharField(blank=True, default='', help_text='Ciudad', max_length=256, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='padre_codigo_postal',
            field=models.CharField(blank=True, default='', help_text='Código  Postal', max_length=128, null=True, verbose_name='Código  Postal'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='padre_colonia',
            field=models.CharField(blank=True, default='', help_text='Colonia', max_length=256, null=True, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='padre_estado',
            field=models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('CDMX', 'Ciudad de México'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Estado de México', 'Estado de México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], default='', help_text='Estado', max_length=256, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='padre_estado_civil',
            field=models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo'), ('Unión Libre', 'Unión Libre'), ('Otro', 'Otro')], default='', help_text='Estado Civil', max_length=128, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='padre_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre', max_length=256, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='padre_ocupacion',
            field=models.CharField(blank=True, default='', help_text='Ocupación', max_length=128, null=True, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='padre_telefono_casa',
            field=models.CharField(blank=True, default='', help_text='Teléfono  de casa', max_length=24, null=True, verbose_name='Teléfono  de casa'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='padre_telefono_particular',
            field=models.CharField(blank=True, default='', help_text='Teléfono  de particular', max_length=24, null=True, verbose_name='Teléfono  particular'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='religion',
            field=models.CharField(blank=True, choices=[('Catolica', 'Catolica'), ('Cristiana', 'Cristiana'), ('Protestante', 'Protestante'), ('Ninguna', 'Ninguna'), ('Otra', 'Otra')], default='', help_text='Religión', max_length=128, null=True, verbose_name='Religión'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_poblacion',
            field=models.CharField(blank=True, choices=[('Rural', 'Rural'), ('Urbana', 'Urbana'), ('Indigena', 'Indigena'), ('Otro', 'Otro')], default='', help_text='Tipo de Población', max_length=128, null=True, verbose_name='Tipo de Población'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_relacion_vives',
            field=models.CharField(blank=True, choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hermano', 'Hermano'), ('Primo', 'Primo'), ('Tío', 'Tío'), ('Abuelo', 'Abuelo'), ('Amigo', 'Amigo'), ('Otro', 'Otro')], default='', help_text='Con quien vives', max_length=128, null=True, verbose_name='Con quien vives'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='vive_madre',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('No sabe', 'No sabe'), ('No', 'No'), ('Sí', 'Sí')], default='', help_text='¿Tu madre vive?', max_length=256, null=True, verbose_name='Vive madre'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='vive_padre',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('No sabe', 'No sabe'), ('No', 'No'), ('Sí', 'Sí')], default='', help_text='¿Tu padre vive?', max_length=256, null=True, verbose_name='Vive padre'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='vives_apellido_materno',
            field=models.CharField(blank=True, default='', help_text='Apellido Materno', max_length=256, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='vives_apellido_paterno',
            field=models.CharField(blank=True, default='', help_text='Apellido Paterno', max_length=256, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='vives_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre', max_length=256, null=True, verbose_name='Nombre'),
        ),
    ]
