# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20170423_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='aborto_considerado',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No'), ('No respondió', 'No respondió')], default='', max_length=1024, null=True, verbose_name='Se consideró el abortó'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='actitud_familiares',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Actitud que espera de los familiares'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='apellido_materno_emergencia',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='apellido_materno_recomendacion',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='apellido_paterno_emergencia',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='apellido_paterno_recomendacion',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='apoyo_papa',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Apoyo del papá'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='calle_emergencia',
            field=models.CharField(blank=True, default='', help_text='Calle', max_length=1024, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='calle_medico',
            field=models.CharField(blank=True, default='', help_text='Calle', max_length=256, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='calle_recomendacion',
            field=models.CharField(blank=True, default='', help_text='Calle', max_length=256, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='canal',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Canal donde se ha visto la referencia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='ciudad_emergencia',
            field=models.CharField(blank=True, default='', help_text='Ciudad', max_length=64, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='ciudad_medico',
            field=models.CharField(blank=True, default='', help_text='Ciudad', max_length=256, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='ciudad_referencia',
            field=models.CharField(blank=True, default='', help_text='Ciudad', max_length=64, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='codigo_postal_emergencia',
            field=models.CharField(blank=True, default='', help_text='Código  Postal', max_length=8, null=True, verbose_name='Código  Postal'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='codigo_postal_medico',
            field=models.CharField(blank=True, default='', help_text='Código  Postal', max_length=8, null=True, verbose_name='Código  Postal'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='codigo_postal_recomendacion',
            field=models.CharField(blank=True, default='', help_text='Código  Postal', max_length=8, null=True, verbose_name='Código  Postal'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='colonia',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='colonia_emergencia',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='colonia_medico',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='comunicacion_padre',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No'), ('No respondió', 'No respondió')], default='', max_length=1024, null=True, verbose_name='Comunicación con el padre'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='duracion_relacion',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Duración de la relación'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='encargado_crianza',
            field=models.CharField(blank=True, default='', help_text='Encargado de tu crianza', max_length=256, null=True, verbose_name='Encargado de tu crianza'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='enfermedades_padecidas',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Enfermedades Padecidas'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_de_animo',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Estado de ánimo'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_emergencia',
            field=models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('CDMX', 'Ciudad de México'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Estado de México', 'Estado de México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], default='', help_text='Estado', max_length=1024, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_medico',
            field=models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('CDMX', 'Ciudad de México'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Estado de México', 'Estado de México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], default='', help_text='Estado', max_length=1024, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_referencia',
            field=models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('CDMX', 'Ciudad de México'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Estado de México', 'Estado de México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], default='', help_text='Estado', max_length=1024, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='familiares',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Familiares que saben del embarazo'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='infancia',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Descripción infancia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='jefe_inmediato',
            field=models.CharField(blank=True, default='', help_text='Jefe inmediato', max_length=256, null=True, verbose_name='Jefe inmediato'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='licenciatura_nombre',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Nombre de la institución escolar'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='licenciatura_tiempo',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('6+', '6+'), ('Otro', 'Otro')], default='Otro', max_length=1024, null=True, verbose_name='Años cursados'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='lugar_trabajo',
            field=models.CharField(blank=True, default='', help_text='Lugar de trabajo', max_length=256, null=True, verbose_name='Lugar trabajo'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='maximo_grado_estudios',
            field=models.CharField(blank=True, choices=[('Sin Estudios', 'Sin Estudios'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Preparatoria', 'Preparatoria'), ('Técnico', 'Técnico'), ('Licenciatura', 'Licenciatura'), ('Postgrado', 'Postgrado'), ('Otro', 'Otro')], default='Otro', max_length=1024, null=True, verbose_name='Máximo grado de estudios'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='nombre_clinica',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Nombre de la clínica'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='nombre_emergencia',
            field=models.CharField(blank=True, default='', help_text='Nombre contacto de emergencia', max_length=64, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='nombre_medico',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Nombre del médico a cargo'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='nombre_recomendacion',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Nombre persona'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='numero_exterior',
            field=models.CharField(blank=True, default='', help_text='Número', max_length=8, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='numero_exterior_medico',
            field=models.CharField(blank=True, default='', help_text='Número de calle', max_length=8, null=True, verbose_name='Número de calle'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='otro_nombre',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Nombre de la institución escolar'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='otro_tiempo',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('6+', '6+'), ('Otro', 'Otro')], default='Otro', max_length=1024, null=True, verbose_name='Años cursados'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='otros',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Otro medio donde se ha visto la referencia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='posgrado_nombre',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Nombre de la institución escolar'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='posgrado_tiempo',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('6+', '6+'), ('Otro', 'Otro')], default='Otro', max_length=1024, null=True, verbose_name='Años cursados'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='preparatoria_nombre',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Nombre de la institución escolar'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='preparatoria_tiempo',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('6+', '6+'), ('Otro', 'Otro')], default='Otro', max_length=1024, null=True, verbose_name='Años cursados'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='primaria_nombre',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Nombre de la institución escolar'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='primaria_tiempo',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('6+', '6+'), ('Otro', 'Otro')], default='Otro', max_length=1024, null=True, verbose_name='Años cursados'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='puesto',
            field=models.CharField(blank=True, default='', help_text='Puesto', max_length=256, null=True, verbose_name='Puesto de trabajo'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='reaccion',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Reacción al embarazo'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='referencia',
            field=models.CharField(blank=True, choices=[('Amistad', 'Amistad'), ('Periodico', 'Periodico'), ('Familiar', 'Familiar'), ('Trabajo', 'Trabajo'), ('Volante', 'Volante'), ('Sopt TV', 'Sopt TV'), ('Página web', 'Página web'), ('Migración', 'Migración'), ('Otro', 'Otro')], default='', help_text='Cómo conoció VIFAC', max_length=256, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='relacion_con_padre',
            field=models.CharField(blank=True, choices=[('Casados por la Iglesia', 'Casados por la Iglesia'), ('Casador por el civil', 'Casador por el civil'), ('Aventura', 'Aventura'), ('Violación', 'Violación'), ('Noviazgo', 'Noviazgo'), ('Otro', 'Otro')], default='', max_length=1024, null=True, verbose_name='Relación con el padre'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='relacion_emergencia',
            field=models.CharField(blank=True, choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hermano', 'Hermano'), ('Primo', 'Primo'), ('Tío', 'Tío'), ('Abuelo', 'Abuelo'), ('Amigo', 'Amigo'), ('Otro', 'Otro')], default='', max_length=1024, null=True, verbose_name='Relación con el contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='relacion_hermanos',
            field=models.CharField(blank=True, help_text='Relación con tus hermanos', max_length=512, null=True, verbose_name='Relación con tus hermanos'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='relacion_madre',
            field=models.CharField(blank=True, help_text='Relación con tu madre', max_length=512, null=True, verbose_name='Relación con tu madre'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='relacion_padre',
            field=models.CharField(blank=True, default='', help_text='Relación con tu padre', max_length=512, null=True, verbose_name='Relación con tu padre'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='relacion_recomendacion',
            field=models.CharField(blank=True, choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hermano', 'Hermano'), ('Primo', 'Primo'), ('Tío', 'Tío'), ('Abuelo', 'Abuelo'), ('Amigo', 'Amigo'), ('Otro', 'Otro')], default='', max_length=1024, null=True, verbose_name='Relación con la persona que recomienda'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='relacion_voluntaria',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No'), ('No respondió', 'No respondió')], default='', max_length=1024, null=True, verbose_name='Relaciones voluntarias'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='secundaria_nombre',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Nombre de la institución escolar'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='secundaria_tiempo',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('6+', '6+'), ('Otro', 'Otro')], default='Otro', max_length=1024, null=True, verbose_name='Años cursados'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tecnica_nombre',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Nombre de la institución escolar'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tecnica_tiempo',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('6+', '6+'), ('Otro', 'Otro')], default='Otro', max_length=1024, null=True, verbose_name='Años cursados'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='telefono_jefe',
            field=models.CharField(blank=True, default='', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_de_ayuda',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('Interna', 'Interna'), ('Externa', 'Externa')], default='', max_length=1024, null=True, verbose_name='Tipo de ayuda'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_embarazo',
            field=models.CharField(blank=True, choices=[('Deseado', 'Deseado'), ('Planeado', 'Planeado'), ('Inesperado', 'Inesperado'), ('Rechazado', 'Rechazado'), ('Otro', 'Otro')], default='', max_length=1024, null=True, verbose_name='Tipo de embarazo'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='trabajado_antes',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('No', 'No'), ('Sí', 'Sí')], default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='trabajo_calle',
            field=models.CharField(blank=True, default='', help_text='Calle', max_length=256, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='trabajo_ciudad',
            field=models.CharField(blank=True, default='', help_text='Ciudad', max_length=256, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='trabajo_codigo_postal',
            field=models.CharField(blank=True, default='', help_text='Código  Postal', max_length=128, null=True, verbose_name='Código  Postal'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='trabajo_colonia',
            field=models.CharField(blank=True, default='', help_text='Colonia', max_length=128, null=True, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='trabajo_estado',
            field=models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('CDMX', 'Ciudad de México'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Estado de México', 'Estado de México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], default='', help_text='Estado', max_length=256, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='violencia_intrafamiliar',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No'), ('No respondió', 'No respondió')], default='', max_length=1024, null=True, verbose_name='Violencia intrafamiliar'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='visto_en',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Dónde se ha visto la referencia'),
        ),
    ]
