# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20170423_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='apellido_materno',
            field=models.CharField(help_text='Apellido Materno', max_length=256, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='apellido_paterno',
            field=models.CharField(help_text='Apellido Paterno', max_length=256, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='edad',
            field=models.IntegerField(help_text='Edad', verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='nombre',
            field=models.CharField(help_text='Nombre', max_length=256, verbose_name='Nombre'),
        ),
    ]
