# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la Escuela', max_length=256, verbose_name='Nombre de la Escuela')),
                ('ciudad', models.CharField(help_text='Ciudad de la escuela', max_length=256, verbose_name='Ciudad')),
                ('estado', models.CharField(help_text='Estado donde está la escuela', max_length=256, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Nombre de categoria', max_length=128, verbose_name='Category Name')),
                ('descripcion', models.CharField(help_text='Descripcion del producto', max_length=256, verbose_name='Description')),
                ('entrego', models.CharField(help_text='Persona que entrego el material', max_length=256, verbose_name='Quien entrego')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholar.Escuela')),
            ],
        ),
    ]
