# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='categoria',
            field=models.CharField(help_text='Nombre de categoria', max_length=128, verbose_name='Categoria de material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.CharField(help_text='Descripcion del producto', max_length=256, verbose_name='Descripcion'),
        ),
    ]
